// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ariashabry/boilerplate-go/helpers/env"
	"github.com/ariashabry/boilerplate-go/helpers/log"
	"github.com/ariashabry/boilerplate-go/infras"
	"github.com/ariashabry/boilerplate-go/internal/domains/product/repository"
	"github.com/ariashabry/boilerplate-go/internal/domains/product/service"
	"github.com/ariashabry/boilerplate-go/internal/handler/product"
	"github.com/ariashabry/boilerplate-go/internal/migration"
	"github.com/ariashabry/boilerplate-go/transport/http"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

// Wiring for everything
func InitializeService(l *log.AppLog) *http.HTTP {
	config := env.Get(l)
	postgresConn := infras.ProvidePostgresConn(config, l)
	productRepositoryPostgresImpl := repository.ProvideProductRepositoryPostgresImpl(postgresConn)
	redis := infras.ProvideRedis(config, l)
	productServiceImpl := service.ProvideProductServiceImpl(productRepositoryPostgresImpl, l, redis)
	productHandler := product.ProvideProductHandler(productServiceImpl, l)
	domainHandlers := http.DomainHandlers{
		ProductHandler: productHandler,
	}
	engine := provideGinEngine()
	router := http.ProvideRouter(domainHandlers, engine)
	httpHTTP := http.ProvideHTTP(postgresConn, config, router, l)
	return httpHTTP
}

// InitializeMigrations wires up the migration service
func InitializeMigrations(l *log.AppLog) *migration.MigrationServiceImpl {
	config := env.Get(l)
	postgresConn := infras.ProvidePostgresConn(config, l)
	migrationServiceImpl := migration.ProvideMigrationService(postgresConn, l)
	return migrationServiceImpl
}

// wire.go:

// Wiring for configurations
var configurations = wire.NewSet(env.Get)

// Wiring for persistences (infrastructure)
var persistences = wire.NewSet(infras.ProvideRedis, infras.ProvidePostgresConn)

// Wiring for product domain
var productDomain = wire.NewSet(service.ProvideProductServiceImpl, wire.Bind(new(service.ProductService), new(*service.ProductServiceImpl)), repository.ProvideProductRepositoryPostgresImpl, wire.Bind(new(repository.ProductRepositoryPostgres), new(*repository.ProductRepositoryPostgresImpl)))

// Wiring for all domains
var domains = wire.NewSet(
	productDomain,
)

// Wiring for HTTP routing
var routing = wire.NewSet(wire.Struct(new(http.DomainHandlers), "*"), product.ProvideProductHandler, provideGinEngine, http.ProvideRouter)

// Wiring for migrations
var migrations = wire.NewSet(migration.ProvideMigrationService)

// provideGinEngine creates a new Gin engine
func provideGinEngine() *gin.Engine {
	return gin.New()
}
